### ISSUE TITLE
Could you provide an osx-arm64 or noarch conda package? 

### ISSUE THREAD

**Issue by FriederikeBrezing** [conda-forge/pyannote.core-feedstock#12]
### Comment:

On conda-forge, there are only conda packages for pyannote.core for osx-64, linux-64 and win-64 but not for osx-arm64. 

Could you please provide a conda package for osx-arm64 as well? 

From the pypi source it even seems as if this could be a noarch package: https://pypi.org/project/pyannote.core/#files

**Comment by tyrius02** [comment]
v5.0.0 should be available as a noarch package.
